config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  devise_for :users
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  

  namespace :vendor do
    resources :products
  end

  namespace :admin do
    resources :users do
      member do
        post :make_vendor
      end
    end
    resources :orders  
  end

  resources :cart_items do
    member do
      post :add_product_to_cart
    end
  end

  resources :orders do
    collection do
      post :place_order
    end
  end

  resources :categories do
    collection do
      get :fetch_products
    end
  end
end

app/models/application_record.rb
# ApplicationRecord class
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
# CartItem class
class CartItem < ApplicationRecord
	belongs_to :product, class_name: 'Vendor::Product'
	validates :product_id, presence: true
	before_save :add_amount

	def add_amount
		self.amount = calculate_amount
	end

	def calculate_amount
		product = Vendor::Product.find(product_id)
		product.price.to_f * quantity.to_f
	end
end

app/models/category.rb
# Category class
class Category < ApplicationRecord
	has_many :products, class_name: 'Vendor::Product'
end

app/models/line_item.rb
# LineItem class
class LineItem < ApplicationRecord
  belongs_to :itemable, polymorphic: true
  belongs_to :product, class_name: 'Vendor::Product'
end

app/models/order.rb
# Order class
class Order < ApplicationRecord
  has_many :line_items, as: :itemable
  belongs_to :user
  after_create_commit :calculate_total_amount

  def calculate_total_amount
    line_items_amount = line_items.map(&:amount).sum
    self.amount = line_items_amount
    save!
  end
end

app/models/role.rb
# Role class
class Role < ApplicationRecord
end

app/models/user.rb
# User class
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :role
  before_validation :set_role
  has_many :products
  has_many :cart_items

  def set_role
    self.role_id = Role.find_by(name: "customer").id
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminsController
	before_action :set_order, only: [:show]

	def index
		@orders = Order.all
	end

	def show
		@line_items = @order.line_items
	end

	private
	def set_order
    @order = Order.find(params[:id])
	end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminsController
	def index
		@users = User.all
	end

	def make_vendor
		user = User.where(id: params[:id])

		if user.update_all(role_id: Role.find_by(name: "vendor").id)
      flash[:success] = 'sucess' 
      redirect_to admin_users_path
    else
      redirect_to admin_users_path
    end
	end
end

app/controllers/admins_controller.rb
#AdminsController
class AdminsController < ApplicationController
  # before_action :authenticate_user!
  
	def index;end
end

app/controllers/application_controller.rb
#ApplicationController
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/cart_items_controller.rb
#CartItemsController
class CartItemsController < ApplicationController
  before_action :authenticate_user!, only: [:add_product_to_cart]
  
  def add_product_to_cart
    return error_message unless current_user
    cart = CartItem.create(user_id: current_user.id, product_id: products_params)

    respond_to do |format|
      format.json { render json: { cart_id: cart.try(:id) }, status: 200 }
    end
  end

  private
  def products_params
    params.require(:id)
  end
end

app/controllers/categories_controller.rb
#CategoriesController
class CategoriesController < ApplicationController
	before_action :load_category

	def fetch_products
		@products = @category.products

		html = render_to_string('shared/_product_page', formats: :html, layout: false)

		respond_to do |format|
      format.json { render json: { html: html }, status: 200 }
    end
	end

	private

	def load_category
		@category = Category.find(category_id)
	end

	def category_id 
		params.require(:category_id)
	end
end

app/controllers/customers_controller.rb
#CustomersController
class CustomersController < ApplicationController
	def index;end
end

app/controllers/home_controller.rb
#HomeController
class HomeController < ApplicationController

	def index
		@products = Vendor::Product.all
		@categories = Category.all
		@cart_items = current_user&.cart_items
	end
end

app/controllers/orders_controller.rb
#OrdersController
class OrdersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def place_order
    ActiveRecord::Base.transaction do
      return error_message unless current_user.present?
      order = Order.create!(user_id: current_user.id)

      order_params.each do |_vale, line_item|
        order.line_items.create!(line_item)
        current_user.cart_items.find_by(
          product_id: line_item[:product_id]
        ).destroy
        line_items_amount = order.line_items.map(&:amount).sum
        order.update!(amount: line_items_amount)
      end
      return success_message if order.present?
    end
  end

  private
  def success_message
    respond_to do |format|
      format.json { render json: { info: 'Thanks For Order !' }, status: 200 }
    end
  end

  def error_message
    respond_to do |format|
      format.json { render json: { error: 'please login before add product to cart' }, status: 200 }
    end
  end

  def order_params
    params.require(:cart_item).permit!
  end
end

app/controllers/vendors_controller.rb
#VendorsController
class VendorsController < ApplicationController
  def index;end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
#CategoriesHelper
module CategoriesHelper
	def category_list
		Category.all.map {|category|  [category.name, category.id]}
	end
end

app/helpers/sessions_helper.rb
#SessionsHelper
module SessionsHelper
	# Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
end

app/views/admin/orders/index.html.erb
<%= javascript_pack_tag 'cart-operation' %>

<div class="box record_detail_box">
  <div class="box-header">
    <div class="listHeaderContainer center" >
      <h3 class="box-title">Listing Order</h3>
    </div>
  </div>
  <div class="box-body no-padding">
    <div class="row">
      <div class="col-md-6 margin listing-form-control">
        <div class="form-group">
          <div class="field">
          </div>
        </div>
      </div>
    </div>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Total Amount</th>
          <th colspan="3" class="text-center">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td><%= order.user.email %></td>
            <td><%= order.amount %></td>
            <td><%= link_to 'Show', admin_order_path(order) %></td>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/show.html.erb
<%= javascript_pack_tag 'cart-operation' %>

<div class="box record_detail_box">
  <div class="box-header">
    <div class="listHeaderContainer center" >
      <h3 class="box-title">Order Details</h3>
    </div>
  </div>
  <div class="box-body no-padding">
    <div class="row">
      <div class="col-md-6 margin listing-form-control">
        <div class="form-group">
          <div class="field">
          </div>
        </div>
      </div>
    </div>

    <div>
      Total Amount: <%= @order.amount %>
    </div>
     <div>
      Total Items: <%= @line_items.map(&:quantity).sum %>
    </div>

    <table class="table table-bordered">

      <thead>
        <tr>
          <th>Quantity</th>
          <th>Amount</th>
          <th>Product Name</th>
          <th>Product Category</th>
        </tr>
      </thead>

      <tbody>
        <% @line_items.each do |order| %>
          <tr>
            <td><%= order.quantity %></td>
            <td><%= order.amount %></td>
            <td><%= order.product.name %></td>
            <td><%= order.product.category.name %></td>
            <td></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/index.html.erb
<%= javascript_pack_tag 'cart-operation' %>

<div class="box record_detail_box">
  <div class="box-header">
    <div class="listHeaderContainer center" >
      <h3 class="box-title">Listing Users</h3>
    </div>
  </div>
  <div class="box-body no-padding">
    <div class="row">
      <div class="col-md-6 margin listing-form-control">
        <div class="form-group">
          <div class="field">
          </div>
        </div>
      </div>
    </div>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Role</th>
          <th colspan="3" class="text-center">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.email %></td>
            <td><%= user.role.name %></td>
            <td class="make-vendor" data-user-id=<%= user.id %>>Make Vendor</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/index.html.erb
<%= javascript_pack_tag 'cart-operation' %>

<div class="main">
  <div class="cart-btn">
    <a href="#" class="cart"><span></span></a>
    <svg version="1.1" class="arrow-icon" x="0px" y="0px"
       width="43.737px" height="20px" viewBox="91.602 355.81 43.737 20" enable-background="new 91.602 355.81 43.737 20"
       xml:space="preserve">
      <path fill="#FFFFFF" d="M135.271,367.059l0.003-0.004c0,0-0.004-0.011-0.013-0.031c-0.013-0.034-0.031-0.066-0.047-0.099
      c-0.036-0.071-0.089-0.165-0.167-0.278c-0.087-0.152-0.193-0.288-0.323-0.398c-0.134-0.142-0.297-0.291-0.496-0.438
      c-0.812-0.601-2.354-1.611-2.354-1.611l-0.003,0.002c-4.075-3.042-8.143-5.811-12.747-8.236c-1.404-0.739-2.59,1.368-1.203,2.157
      c3.747,2.133,7.099,4.48,10.398,7.033c-5.68-0.152-11.391,0.137-17.049,0.524c-3.574,0.244-7.146,0.567-10.707,0.949
      c-2.722,0.292-5.863,0.299-8.465,1.171c-0.756,0.253-0.616,1.331,0.185,1.374c2.904,0.157,6.049-0.513,8.961-0.709
      c3.465-0.232,6.933-0.389,10.403-0.516c5.564-0.203,11.163-0.353,16.731-0.064c-4.195,1.61-8.221,3.378-12.263,5.646
      c-1.393,0.782-0.148,2.855,1.255,2.127c5.506-2.858,10.946-4.785,16.846-6.652c0.605-0.192,0.928-0.63,1.032-1.117
      C135.352,367.62,135.365,367.333,135.271,367.059z"/>
    </svg><!-- /.arrow-icon -->
    
    <svg version="1.1" class="cart-icon" x="0px" y="0px"
       width="27.911px" height="28px" viewBox="313.963 302.125 27.911 28" enable-background="new 313.963 302.125 27.911 28"
       xml:space="preserve">
      <path fill="#FFFFFF" d="M341.263,311.6c-0.551-0.683-1.378-1.075-2.271-1.075h-3.919v-1.4c0.006-3.858-3.23-7-7.198-7
      s-7.204,3.142-7.204,7v1.4h-3.913c-0.893,0-1.72,0.391-2.271,1.075c-0.551,0.683-0.739,1.56-0.524,2.403l3.599,14
      c0.32,1.251,1.472,2.122,2.794,2.122h15.036c1.323,0,2.475-0.871,2.794-2.122l3.599-14
      C342.002,313.16,341.814,312.289,341.263,311.6z M323.554,309.125c0-2.315,1.94-4.2,4.321-4.2s4.321,1.885,4.321,4.2v1.4h-8.643
      V309.125z M335.393,327.325h-15.036l-3.599-14h3.919v2.8c0,0.772,0.645,1.4,1.439,1.4s1.439-0.628,1.439-1.4v-2.8h8.643v2.8
      c0,0.772,0.645,1.4,1.439,1.4s1.439-0.628,1.439-1.4v-2.8h3.919L335.393,327.325z"/>
    </svg>
  </div>
</div>

<div id="wrapper">
  <div id="sidebar">
    <div id="cart">
    </div>
    <h3>CATEGORIES</h3>
    <div class="checklist categories">
      <ul>
        <% @categories.each do |category| %>
          <li><a href="" class="product-categories" data-category-id="<%= category.id %>"><span></span><%= category.name %></a></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="product-list">
    <%= render 'shared/product_page' %>
  </div>
</div>

<body class="cart-drawer-push">
  <div class="container">
    <div class="cart-drawer cart-drawer-right"> 
      <span>Your Cart</span>
      <div class="close-btn">
        <svg version="1.1" class="close-icon" x="0px" y="0px"
           width="18px" height="18px" viewBox="312 387 18 18" enable-background="new 312 387 18 18" xml:space="preserve">
          <path fill="#E55959" d="M312.54,404.46c0.36,0.36,0.84,0.54,1.26,0.54c0.42,0,0.9-0.18,1.26-0.54l5.94-5.94l5.94,5.94
          c0.36,0.36,0.84,0.54,1.26,0.54c0.42,0,0.9-0.18,1.26-0.54c0.72-0.72,0.72-1.86,0-2.52l-5.94-5.94l5.94-5.94
          c0.72-0.72,0.72-1.86,0-2.52c-0.72-0.72-1.86-0.72-2.52,0l-5.94,5.94l-5.94-5.94c-0.72-0.72-1.86-0.72-2.52,0
          c-0.72,0.72-0.72,1.86,0,2.52l5.94,5.94l-5.94,5.94C311.82,402.66,311.82,403.8,312.54,404.46z"/>
        </svg>
      </div>

      <div id="ex1" style="height: 95%;overflow-y: scroll;">
        <% if @cart_items.present? %>
          <form id="checkout-order-form">
            <div class="">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total Cost</th>
                  </tr>
                </thead>
                <tbody>
                  <% @cart_items.each_with_index do |cart_item, index| %>
                    <tr class="cart-item">
                      <input type="hidden" name="cart_item[<%= index %>]product_id" value=<%= cart_item.product.id %>>

                      <input type="hidden" value=<%= cart_item.product.price %>>

                      <td><span><%= cart_item.product.name %></span></td>
                      <td><span class="price" data-value=<%= cart_item.product.price %>><%= cart_item.product.price %></span></td>
                      <td><input type="number" name="cart_item[<%= index %>]quantity" value=1 class="qty"></td>
                      <td><input type="number" name="cart_item[<%= index %>]amount"class="item-total" value="<%= cart_item.product.price %>" data-item-value=<%= cart_item.product.price %>></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>

              <div class="" style="float: right;">
                <label>Total: </label> <strong><span class="total">0.0</span></strong>
              </div>
            </div>
          <% else %>
              <span class="empty">No items in cart.</span>
          <% end %>

          <div class="" style="margin-top: 60px;">
            <button class="btn btn-sm btn-primary place-your-order">Place Your Order</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</body>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <address>
          <strong>Website:</strong><br />
          <a href="#">www.aboutsagar.com</a>
        </address>
        <address>
          <strong>Address:</strong><br />
          Flat NO.3, Yamunai Niwas, Sangam Chowk<br />
          Kothrud,Pune 411038.
        </address>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="site-header"> 
  <nav class="navbar navbar-default">
    <div class="header-inner">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="brand">
              <a href="http://www.inforest.com/" title="Example Home" rel="home"><img src="/cart.jpg" class="" border="0" height="90px;"></a>
            </div>
            <nav  id="nav-wrap" class="main-nav"> <a id="toggle-btn" href="#"><i class="fa fa-bars"></i> </a>
              <ul class="sf-menu">
                <li class="current"> <a href="/">Home</a> </li>
                <% if current_user %>
                  <li> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %> </li>
                  <li> <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                   <% if current_user&.role&.name == 'vendor'%>
                     <li> <%= link_to 'Products', vendor_products_path, :class => 'navbar-link' %></li>
                   <%elsif current_user&.role&.name == 'admin'%>
                     <li> <%= link_to 'Users', admin_users_path, :class => 'navbar-link' %></li>
                     <li> <%= link_to 'Orders', admin_orders_path, :class => 'navbar-link' %></li>
                   <%end%>
                <% else %>
                  <li> <%= link_to 'Sign Up', new_user_registration_path %></li>
                  <li> <%= link_to 'Sign In', new_user_session_path %> </li>
                <% end %>
              </ul>
            </nav> 
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minecart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/shared/_product_page.html.erb
<div id="">
  <div class="container">
    <div class="col-sm-12">
      <div class="row">
      <% if @products.present? %>
      <% @products.each do |product| %>
        <div class="col-sm-6">
          <div class="card">
          <%= image_tag product.image.variant(resize: "320x200") %>
          <div class="card-body">
            <h4 class="card-title"><%= product.name %></h4>
            <h6 class="card-subtitle mb-2 text-muted"><%= product.price %>$</h6>
            <p class="card-text"><%= product.description %> </p>
            <a class="add-to-cart" data-product-id=<%= product.id %>>add to cart</a>
          </div>
          </div>
        </div>
      <% end %>
      <% else %>
        <span class="empty">No products.</span>
      <% end %>  
      </div>
    </div>
  </div>
</div>